environment:
    type: "CPP"
gamma: 0.99
lamda: 0.99
updates: 3000
epochs: 5
n_workers: 8
worker_steps: 80
n_mini_batch: 4
value_loss_coefficient: 0.3
hidden_layer_size: 576
max_grad_norm: 0.5
transformer:
    num_blocks: 3
    embed_dim: 576
    num_heads: 48
    memory_length: 40
    positional_encoding: "relative" # options: "" "relative" "learned"
    layer_norm: "pre" # options: "" "pre" "post"
    gtrxl: True
    gtrxl_bias: 0.0
learning_rate_schedule:
    initial: 1.0e-4
    final: 1.0e-8
    power: 1.0
    max_decay_steps: 2700
beta_schedule:
    initial: 0.01
    final: 0.00001
    power: 1.0
    max_decay_steps: 2700
clip_range_schedule:
    initial: 0.1
    final: 0.1
    power: 1.0
    max_decay_steps: 1800